package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/UNKNOWN.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/jenkins/workspace/8-2-build-windows-x64-cygwin/jdk8u351/2908/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Thursday, September 15, 2022 2:59:35 AM UTC
*/

public interface UNKNOWN
{

  /**
   * XXX
   */
  public static final short value = (short)(5);
}
